tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash-completion"
brew "bash-git-prompt"
brew "git"
brew "mas"
brew "node@8"
brew "yarn"
cask "docker"
cask "intellij-idea"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "webstorm"
mas "Xcode", id: 497799835
